[package]
name = "it-poker-bot"
version = "0.1.0"
authors = ["lazymechanic"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
